### PR TITLE
Update whacks for =

### PR DESCRIPTION
**Pull request by dwilsonactual**

### CODE REVIEW

**Comment by T-Hugs** [comment]
This is a breaking change - needs to rev the major version.

**Review by T-Hugs — CHANGES_REQUESTED** [review]
This is not good.

**Comment by dwilsonactual** [comment]
@T-Hugs I've updated the PR to bump the major version, plz :stamp:

**Comment by T-Hugs** [comment]
You didn't address my second comment.

**Comment by dwilsonactual** [comment]
> This is not good.

@T-Hugs maybe I don't know how to GitHub, but what exactly isn't good?

**Comment by T-Hugs** [comment]
The change

**Pull request closed without merging**
